language: dart
sudo: false
dart:
  - dev
cache:
  directories:
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.pub-cache/hosted
    - third_party/pkg/dev_compiler/node_modules
before_install:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"
  - 'gclient config --spec=''solutions = [ { "name": ".", "url": "git@github.com:dart-lang/sdk.git", "deps_file": "DEPS", "managed": False, "custom_vars": { "dart_root": "." } } ]'''
  - gclient sync
  - ./tools/build.py -m release
  - export PATH=`pwd`/out/ReleaseX64/dart-sdk/bin:"$PATH"
  - dart --version
  - cd third_party/pkg/dev_compiler
  - pub global activate dart_coveralls
  - export CHROME_CANARY_BIN=`./tool/get_chrome_canary.sh`
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - nvm install 5.5.0
  - npm install
script:
  - if [[ -z "$TEST" ]]; then ./tool/presubmit.sh ; fi
  - if [[ "$TEST" == coverage ]]; then ./tool/build_sdk.sh && ./tool/coverage.sh ; fi
  - if [[ "$TEST" == node ]]; then ./tool/node_test.sh ; fi
env:
  - ANALYZER=master
  - TEST=coverage
  - TEST=node
matrix:
  allow_failures:
    - env: ANALYZER=master
    - env: TEST=node
